name: Publish packages to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/com.timeslip.microframework.core/**'
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Publish Core'
        required: true
        default: 'com.timeslip.microframework.core'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: 
          - name: com.timeslip.microframework.core
            path: 'packages/com.timeslip.microframework.core/'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com/'

    - run: npm install --only=prod
    - name: Debugging Matrix Values
      run: |
        echo "Package Name: ${{ matrix.package.name }}"
        echo "Package Path: ${{ matrix.package.path }}"
    - name: Build and publish ${{ matrix.package.name }}
      if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.package_name == matrix.package.name)
      run: |
        echo "Checking if changes match ${{ matrix.package.path }}"
        cd ${{ matrix.package.path }}
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
