name: Publish packages to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/com.timeslip.microframework.core/**'
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Publish Core'
        required: true
        default: 'com.timeslip.microframework.core'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: 
          - name: com.timeslip.microframework.core
            path: 'packages/com.timeslip.microframework.core/'
    steps:
    - uses: actions/checkout@v3
    
    - name: Debugging Event Information
      run: |
        echo "Event Name: ${{ github.event_name }}"
        if [ "$GITHUB_EVENT_NAME" == "push" ]; then
          echo "Push event detected"
          for file in $(git diff-tree --no-commit-id --name-only -r HEAD~1 HEAD); do
            echo "Changed file: $file"
          done
        elif [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
          echo "Workflow dispatch event detected"
          echo "Specified package: ${{ github.event.inputs.package_name }}"
        fi
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com/'

    - run: npm install --only=prod
    
    - name: Debugging Matrix Values
      run: |
        echo "Package Name: ${{ matrix.package.name }}"
        echo "Package Path: ${{ matrix.package.path }}"
        
    - name: Create .npmrc file
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
        echo "@a13782425:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and publish ${{ matrix.package.name }}
      if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.package_name == matrix.package.name)
      run: |
        echo "Checking if changes match ${{ matrix.package.path }}"
        cd ${{ matrix.package.path }}
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
